[[rulesets]]
group = "ğŸ¯ Ù…Ø³ØªÙ‚ÛŒÙ…"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "â“‚ï¸ Ù…Ø§ÛŒÚ©Ø±ÙˆØ³Ø§ÙØª"
ruleset = "rules/MSServices.list"

[[rulesets]]
group = "ğŸ¯ Ù…Ø³ØªÙ‚ÛŒÙ…"
ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "ğŸ›‘ Ù…Ø³Ø¯ÙˆØ¯"
ruleset = "rules/NobyDa/Surge/AdRule.list"

[[rulesets]]
group = "ğŸ›‘ Ù…Ø³Ø¯ÙˆØ¯"
ruleset = "rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list"

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

[[rulesets]]
group = "ğŸŒ Ø±Ø³Ø§Ù†Ù‡ Ù‡Ø§ÛŒ Ø®Ø§Ø±Ø¬ÛŒ"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ“² ØªÙ„Ú¯Ø±Ø§Ù…"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ”° Ø§Ù†ØªØ®Ø§Ø¨ Ù†ÙˆØ¯"
ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ Ø§Ù¾Ù„"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list"

[[rulesets]]
group = "ğŸ¯ Ù…Ø³ØªÙ‚ÛŒÙ…"
ruleset = "rules/DivineEngine/Surge/Ruleset/Iran.list"

[[rulesets]]
group = "ğŸ¯ Ù…Ø³ØªÙ‚ÛŒÙ…"
ruleset = "rules/NobyDa/Surge/Download.list"

[[rulesets]]
group = "ğŸ¯ Ù…Ø³ØªÙ‚ÛŒÙ…"
ruleset = "[]GEOIP,IR"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

